version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "game-server-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-coa3xt11bmi8"
s3_prefix = "game-server-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"finesse_connections\""

