version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "game-server-stack"
s3_bucket = "mouse-dragons-sam"
s3_prefix = "game-server-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

